services:
  - type: web
    name: api-trufas
    env: node
    plan: free
    port: 3001
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
